# Generated by Django 4.2.5 on 2023-11-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('perfum_name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('perfum_count', models.IntegerField()),
                ('perfum_sum', models.IntegerField()),
            ],
        ),
    ]
