# Generated by Django 4.2.5 on 2023-12-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='perfum_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='perfum_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='perfum_sum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
