# Generated by Django 4.2.5 on 2023-11-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization_Registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
