# Generated by Django 4.2.5 on 2023-12-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_page', '0002_alter_shoppingcart_perfum_count_and_more'),
        ('Authorization_Registration', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shopping_cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_cart_page.shoppingcart'),
        ),
    ]
