# Generated by Django 4.2.5 on 2023-11-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfum',
            options={'verbose_name': 'Парфум', 'verbose_name_plural': 'Парфуми'},
        ),
        migrations.AddField(
            model_name='perfum',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='perfum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='perfum',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='perfum',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
    ]
