# Generated by Django 4.2.5 on 2023-11-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_page', '0002_alter_perfum_options_perfum_description_perfum_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfum',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='perfum',
            name='name',
            field=models.CharField(max_length=300, verbose_name="Ім'я"),
        ),
    ]
