# Generated by Django 4.2.5 on 2024-02-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_page', '0004_alter_perfum_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfum',
            name='number_in_cart',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
