# Generated by Django 4.2.5 on 2024-02-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_page', '0005_perfum_number_in_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfum',
            name='count_in_cart',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
